package com.scto.codelikebastimove.core.templates.impl

import com.scto.codelikebastimove.core.datastore.GradleInfo
import com.scto.codelikebastimove.core.datastore.ProjectTemplateType
import com.scto.codelikebastimove.core.datastore.TemplateInfo
import com.scto.codelikebastimove.core.datastore.VersionCatalog
import com.scto.codelikebastimove.core.datastore.VersionCatalogBundle
import com.scto.codelikebastimove.core.datastore.VersionCatalogEntry
import com.scto.codelikebastimove.core.datastore.VersionCatalogLibrary
import com.scto.codelikebastimove.core.datastore.VersionCatalogPlugin
import com.scto.codelikebastimove.core.templates.api.ProjectConfig
import com.scto.codelikebastimove.core.templates.api.ProjectFile
import com.scto.codelikebastimove.core.templates.api.ProjectTemplate

abstract class BaseVersionCatalogTemplate : ProjectTemplate {

  abstract val templateId: String
  abstract val templateVersion: String
  abstract val templateType: ProjectTemplateType
  abstract val features: List<String>

  open val gradleInfo: GradleInfo =
    GradleInfo(
      gradleVersion = "8.10.2",
      distributionUrl = "https://services.gradle.org/distributions/gradle-8.10.2-bin.zip",
      agpVersion = "8.7.3",
      kotlinVersion = "2.1.0",
      composeBomVersion = "2024.12.01",
      usesVersionCatalog = true,
    )

  open val minSdk: Int = 24
  open val targetSdk: Int = 35
  open val compileSdk: Int = 35

  abstract fun getVersionCatalog(): VersionCatalog

  fun getTemplateInfo(): TemplateInfo =
    TemplateInfo(
      id = templateId,
      name = name,
      description = description,
      version = templateVersion,
      lastUpdated = System.currentTimeMillis(),
      templateType = templateType,
      gradleInfo = gradleInfo,
      versionCatalog = getVersionCatalog(),
      supportedLanguages = listOf("Kotlin", "Java"),
      features = features,
      minSdk = minSdk,
      targetSdk = targetSdk,
      compileSdk = compileSdk,
    )

  protected fun generateVersionCatalogToml(config: ProjectConfig): ProjectFile {
    val catalog = getVersionCatalog()
    return ProjectFile("gradle/libs.versions.toml", catalog.toTomlContent())
  }

  protected fun generateGradleWrapper(config: ProjectConfig): List<ProjectFile> {
    return listOf(
      ProjectFile("gradle/wrapper", "", isDirectory = true),
      generateGradleWrapperProperties(config),
      generateGradlewScript(),
      generateGradlewBatScript(),
    )
  }

  protected fun generateGradleWrapperProperties(config: ProjectConfig): ProjectFile {
    val content =
      """
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-${gradleInfo.gradleVersion}-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""
        .trimIndent()
    return ProjectFile("gradle/wrapper/gradle-wrapper.properties", content)
  }

  protected fun generateGradlewScript(): ProjectFile {
    val content =
      """
#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX://shell://features:
#         * functions;
#         * expansions «${'$'}var», «${'$'}{var}», «${'$'}{var:-default}», «${'$'}{var+substitute}»,
#           «${'$'}{var#eli}», «${'$'}{var%%eli}», and «${'$'}( command )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX://shell, so it avoids://extensions provided
#       by Bash, Ksh, etc; in particular://arrays are avoided.
#
#       The "traditional" style://of://command://line://handling://uses://a://hierarchical
#       conditional block for each option. In sh, things are easier....
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: ${'$'}0 may be a link
app_path=${'$'}0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${'$'}{app_path%"${'$'}{app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "${'$'}app_path" ]
do
    ls=${'$'}( ls -ld "${'$'}app_path" )
    link=${'$'}{ls#*' -> '}
    case ${'$'}link in             #(
      /*)   app_path=${'$'}link ;; #(
      *)    app_path=${'$'}APP_HOME${'$'}link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${'$'}{0##*/}
# Discard cd standard output in case ${'$'}CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=${'$'}( cd "${'$'}{APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "${'$'}*"
} >&2

die () {
    echo
    echo "${'$'}*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "${'$'}( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=${'$'}APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "${'$'}JAVA_HOME" ] ; then
    if [ -x "${'$'}JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=${'$'}JAVA_HOME/jre/sh/java
    else
        JAVACMD=${'$'}JAVA_HOME/bin/java
    fi
    if [ ! -x "${'$'}JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: ${'$'}JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "${'$'}cygwin" && ! "${'$'}darwin" && ! "${'$'}nonstop" ; then
    case ${'$'}MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=${'$'}( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case ${'$'}MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "${'$'}MAX_FD" ||
            warn "Could not set maximum file descriptor limit to ${'$'}MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...://properties
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "${'$'}cygwin" || "${'$'}msys" ; then
    APP_HOME=${'$'}( cygpath --path --mixed "${'$'}APP_HOME" )
    CLASSPATH=${'$'}( cygpath --path --mixed "${'$'}CLASSPATH" )

    JAVACMD=${'$'}( cygpath --unix "${'$'}JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case ${'$'}arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${'$'}{arg#)}                         # remove everything from / onwards
                    t=/${'$'}{t##}                          # strip all leading non-backslashes
                    t=${'$'}{t%"${'$'}{t#??}"}                       # remove all but first two characters
                    [ -e "${'$'}t" ] ;;                      # test if the path exists #(
              *)    false ;;
            esac
        then
            arg=${'$'}( cygpath --path --ignore --mixed "${'$'}arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary, temporary until we get them all.
        shift                                       # remove old arg
        set -- "${'$'}@" "${'$'}arg"                            # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, GRADLE_OPTS, and optsEnvironmentVar are not://double-quoted
#     to allow://the://shell://to://expand://them://to://multiple://arguments.
#   * The rest are double-quoted.
set -- \
        -classpath "${'$'}CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "${'$'}@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://1://it://outputs://one://arg per line, with the quotes and special://chars://removed.
#
# In Bash we could simply go:
#
#   readarray://ARGS://< <( xargs -n1 <<<"${'$'}DEFAULT_JVM_OPTS ${'$'}JAVA_OPTS ${'$'}GRADLE_OPTS" ) &&
#   set -- "${'$'}{ARGS[@]}" "${'$'}@"
#
# but://POSIX://://shell://has://no://arrays.
eval "set -- $(
        printf '%s\n' "${'$'}DEFAULT_JVM_OPTS ${'$'}JAVA_OPTS ${'$'}GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~'~'\\''~g; s~.*~'&'~; ' |
        tr '\n' ' '
    )" '"${'$'}@"'

exec "${'$'}JAVACMD" "${'$'}@"
"""
        .trimIndent()
    return ProjectFile("gradlew", content)
  }

  protected fun generateGradlewBatScript(): ProjectFile {
    val content =
      """
@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
@rem This is normally unused
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo. 1>&2
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. 1>&2
echo. 1>&2
echo Please set the JAVA_HOME variable in your environment to match the 1>&2
echo location of your Java installation. 1>&2

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo. 1>&2
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME% 1>&2
echo. 1>&2
echo Please set the JAVA_HOME variable in your environment to match the 1>&2
echo location of your Java installation. 1>&2

goto fail

:execute
@rem Setup the command line

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar


@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if %ERRORLEVEL% equ 0 goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
if not ""=="%GRADLE_EXIT_CONSOLE%" exit %EXIT_CODE%
exit /b %EXIT_CODE%

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
"""
        .trimIndent()
    return ProjectFile("gradlew.bat", content)
  }

  protected fun generateSettingsGradleKts(config: ProjectConfig): ProjectFile {
    val content =
      """
pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "${config.projectName}"
include(":app")
"""
        .trimIndent()
    return ProjectFile("settings.gradle.kts", content)
  }

  protected fun generateSettingsGradleGroovy(config: ProjectConfig): ProjectFile {
    val content =
      """
pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'com\\.google.*'
                includeGroupByRegex 'androidx.*'
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = '${config.projectName}'
include ':app'
"""
        .trimIndent()
    return ProjectFile("settings.gradle", content)
  }

  protected fun generateRootBuildGradleKts(config: ProjectConfig): ProjectFile {
    val content =
      """
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
}
"""
        .trimIndent()
    return ProjectFile("build.gradle.kts", content)
  }

  protected fun generateRootBuildGradleGroovy(config: ProjectConfig): ProjectFile {
    val content =
      """
plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.kotlin.android apply false
    alias libs.plugins.kotlin.compose apply false
}
"""
        .trimIndent()
    return ProjectFile("build.gradle", content)
  }

  protected fun generateGradleProperties(config: ProjectConfig): ProjectFile {
    val content =
      """
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.defaults.buildfeature.buildconfig=true
"""
        .trimIndent()
    return ProjectFile("gradle.properties", content)
  }

  protected fun generateGitignore(config: ProjectConfig): ProjectFile {
    val content =
      """
*.iml
.gradle
/local.properties
/.idea
.DS_Store
/build
/captures
.externalNativeBuild
.cxx
local.properties
"""
        .trimIndent()
    return ProjectFile(".gitignore", content)
  }

  protected fun generateProguardRules(config: ProjectConfig): ProjectFile {
    val content =
      """
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
"""
        .trimIndent()
    return ProjectFile("app/proguard-rules.pro", content)
  }

  companion object {
    fun createBaseComposeVersionCatalog(): VersionCatalog {
      return VersionCatalog(
        versions =
          listOf(
            VersionCatalogEntry("agp", "8.7.3"),
            VersionCatalogEntry("kotlin", "2.1.0"),
            VersionCatalogEntry("coreKtx", "1.15.0"),
            VersionCatalogEntry("lifecycleRuntimeKtx", "2.8.7"),
            VersionCatalogEntry("activityCompose", "1.9.3"),
            VersionCatalogEntry("composeBom", "2024.12.01"),
            VersionCatalogEntry("junit", "4.13.2"),
            VersionCatalogEntry("junitVersion", "1.2.1"),
            VersionCatalogEntry("espressoCore", "3.6.1"),
          ),
        libraries =
          listOf(
            VersionCatalogLibrary("androidx-core-ktx", "androidx.core", "core-ktx", "coreKtx"),
            VersionCatalogLibrary(
              "androidx-lifecycle-runtime-ktx",
              "androidx.lifecycle",
              "lifecycle-runtime-ktx",
              "lifecycleRuntimeKtx",
            ),
            VersionCatalogLibrary(
              "androidx-activity-compose",
              "androidx.activity",
              "activity-compose",
              "activityCompose",
            ),
            VersionCatalogLibrary(
              "androidx-compose-bom",
              "androidx.compose",
              "compose-bom",
              "composeBom",
            ),
            VersionCatalogLibrary("androidx-ui", "androidx.compose.ui", "ui", "composeBom"),
            VersionCatalogLibrary(
              "androidx-ui-graphics",
              "androidx.compose.ui",
              "ui-graphics",
              "composeBom",
            ),
            VersionCatalogLibrary(
              "androidx-ui-tooling",
              "androidx.compose.ui",
              "ui-tooling",
              "composeBom",
            ),
            VersionCatalogLibrary(
              "androidx-ui-tooling-preview",
              "androidx.compose.ui",
              "ui-tooling-preview",
              "composeBom",
            ),
            VersionCatalogLibrary(
              "androidx-ui-test-manifest",
              "androidx.compose.ui",
              "ui-test-manifest",
              "composeBom",
            ),
            VersionCatalogLibrary(
              "androidx-ui-test-junit4",
              "androidx.compose.ui",
              "ui-test-junit4",
              "composeBom",
            ),
            VersionCatalogLibrary(
              "androidx-material3",
              "androidx.compose.material3",
              "material3",
              "composeBom",
            ),
            VersionCatalogLibrary("junit", "junit", "junit", "junit"),
            VersionCatalogLibrary("androidx-junit", "androidx.test.ext", "junit", "junitVersion"),
            VersionCatalogLibrary(
              "androidx-espresso-core",
              "androidx.test.espresso",
              "espresso-core",
              "espressoCore",
            ),
          ),
        plugins =
          listOf(
            VersionCatalogPlugin("android-application", "com.android.application", "agp"),
            VersionCatalogPlugin("kotlin-android", "org.jetbrains.kotlin.android", "kotlin"),
            VersionCatalogPlugin("kotlin-compose", "org.jetbrains.kotlin.plugin.compose", "kotlin"),
          ),
        bundles =
          listOf(
            VersionCatalogBundle(
              "compose",
              listOf(
                "androidx-ui",
                "androidx-ui-graphics",
                "androidx-ui-tooling-preview",
                "androidx-material3",
              ),
            ),
            VersionCatalogBundle(
              "compose-debug",
              listOf("androidx-ui-tooling", "androidx-ui-test-manifest"),
            ),
          ),
      )
    }

    fun createBaseViewVersionCatalog(): VersionCatalog {
      return VersionCatalog(
        versions =
          listOf(
            VersionCatalogEntry("agp", "8.7.3"),
            VersionCatalogEntry("kotlin", "2.1.0"),
            VersionCatalogEntry("coreKtx", "1.15.0"),
            VersionCatalogEntry("appcompat", "1.7.0"),
            VersionCatalogEntry("material", "1.12.0"),
            VersionCatalogEntry("constraintlayout", "2.2.0"),
            VersionCatalogEntry("lifecycle", "2.8.7"),
            VersionCatalogEntry("junit", "4.13.2"),
            VersionCatalogEntry("junitVersion", "1.2.1"),
            VersionCatalogEntry("espressoCore", "3.6.1"),
          ),
        libraries =
          listOf(
            VersionCatalogLibrary("androidx-core-ktx", "androidx.core", "core-ktx", "coreKtx"),
            VersionCatalogLibrary(
              "androidx-appcompat",
              "androidx.appcompat",
              "appcompat",
              "appcompat",
            ),
            VersionCatalogLibrary(
              "material",
              "com.google.android.material",
              "material",
              "material",
            ),
            VersionCatalogLibrary(
              "androidx-constraintlayout",
              "androidx.constraintlayout",
              "constraintlayout",
              "constraintlayout",
            ),
            VersionCatalogLibrary(
              "androidx-lifecycle-runtime-ktx",
              "androidx.lifecycle",
              "lifecycle-runtime-ktx",
              "lifecycle",
            ),
            VersionCatalogLibrary(
              "androidx-lifecycle-livedata-ktx",
              "androidx.lifecycle",
              "lifecycle-livedata-ktx",
              "lifecycle",
            ),
            VersionCatalogLibrary(
              "androidx-lifecycle-viewmodel-ktx",
              "androidx.lifecycle",
              "lifecycle-viewmodel-ktx",
              "lifecycle",
            ),
            VersionCatalogLibrary("junit", "junit", "junit", "junit"),
            VersionCatalogLibrary("androidx-junit", "androidx.test.ext", "junit", "junitVersion"),
            VersionCatalogLibrary(
              "androidx-espresso-core",
              "androidx.test.espresso",
              "espresso-core",
              "espressoCore",
            ),
          ),
        plugins =
          listOf(
            VersionCatalogPlugin("android-application", "com.android.application", "agp"),
            VersionCatalogPlugin("kotlin-android", "org.jetbrains.kotlin.android", "kotlin"),
          ),
        bundles =
          listOf(
            VersionCatalogBundle(
              "android-core",
              listOf(
                "androidx-core-ktx",
                "androidx-appcompat",
                "material",
                "androidx-constraintlayout",
              ),
            ),
            VersionCatalogBundle(
              "lifecycle",
              listOf(
                "androidx-lifecycle-livedata-ktx",
                "androidx-lifecycle-viewmodel-ktx",
                "androidx-lifecycle-runtime-ktx",
              ),
            ),
          ),
      )
    }
  }
}
